version: '2.4'

services:
    consul:
        image: consul:1.8.4
        container_name: consul
        ports:
            - 8500:8500
        environment: 
            - CONSUL_ALLOW_PRIVILEGED_PORTS='127.0.0.1'
        volumes:
            - ./consul/config:/consul/config
            - ./consul/data:/consul/data
        command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/consul.json

    vault:
        image: vault:1.5.3
        container_name: vault
        ports:
            - "8200:8200"
        environment:
            - VAULT_ADDR=http://127.0.0.1:8200
            - VAULT_API_ADDR=http://127.0.0.1:8200
        restart: always
        volumes:
            - ./vault/config:/vault/config
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault.hcl
        depends_on:
            - consul