version: '2.4'

services:
    vault:
        image: vault:1.5.3
        container_name: vault
        ports:
            - "8200:8200"
        restart: always
        volumes:
            - ./data/logs:/vault/logs
            - ./data/file:/vault/file
            - ./data/config:/vault/config
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault.hcl
